import numpy as np
import math

class Utils:

    def calc_distance(self, x, y):
        """Calculates Euclidian distance between two planar data points"""
        return np.linalg.norm(x-y)
    
    def calc_circumradius(self, x, y, z):
        """Calculates circumradius of the circumcircle generated by three coordinates"""
        a = Utils.calc_distance(self, x, y)
        b = Utils.calc_distance(self, x, z)
        c = Utils.calc_distance(self, y, z)

        return (a*b*c) / (((a+b+c))*(b+c-a)*(c+a-b)*(a+b-c))**(1/2)
    
    def calc_triangle_area(self, x, y, z):
        """Calculates the area of a triangle using cross product"""
        return 0.5 * np.abs(np.cross(x-y, x-z))

    def minimum_distance(pointA, pointB, length):
        """Calculates the distance and compares it with parameter length"""
        if length < math.dist(pointA,pointB):
            return True
        return False

    def maximum_distance(pointA, pointB, length):
        """Calculates the distance and compares it with parameter length"""
    if length > math.dist(pointA, pointB):
        return True
    return False
